### ISSUE TITLE
i have no clue how to work this

### ISSUE THREAD

**Issue by applez1234** [IceDynamix/qua3osu#3]
hi. im trying to convert some cool sv map i found from quaver to osu mania but everytime  i try to open the .exe it just closes. im not sure if thats supposed to happen but if theres any instructions on how to use this i would like to know

**Comment by IceDynamix** [comment]
in case youre unfamiliar with running a program through the command line:

drag your .qp file onto the .exe and a .osz should pop out

https://user-images.githubusercontent.com/22303902/140838272-28793396-ce55-42d4-a69f-f2f90f6187a5.mp4

**Comment by applez1234** [comment]
i have a follow up question. how do i get a qp file from the game?
